<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
	<Actions category="Scripts">
		<text>Batch Manager</text>

		<Action name="open_rucksack">
			<icon></icon>
			<text>Open Rucksack</text>
			<whatsThis></whatsThis>
			<toolTip></toolTip>
			<iconText></iconText>
			<activationFlags>0</activationFlags>
			<activationConditions>0</activationConditions>
			<shortcut>r</shortcut>
			<isCheckable>false</isCheckable>
			<statusTip></statusTip>
		</Action>
	</Actions>
</ActionCollection>
